version: "3"

services:
  core:
    build:
      context: ./core
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - "./core:/app"

  db:
    build:
      context: ./db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  udp_listener:
    build:
      context: ./udp_listener
    volumes:
      - "./udp_listener:/app"
    ports:
      - 0.0.0.0:5005-5100:5005-5100
      - 0.0.0.0:5005-5100:5005-5100/udp

  ws:
    build:
      context: ./ws
    volumes:
      - "./ws:/app"
    ports:
      - 0.0.0.0:5004:5004
      - 0.0.0.0:5004:5004/udp
      - 0.0.0.0:8080:8080

volumes:
  pgdata:
