version: "3"

services:
  server:
    build:
      context: ./server/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3001:3001"
    networks:
      - appnetwork
    links:
      - react-client

  react-client:
    build:
      context: ./client/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge
