version: "3"

services:
  core:
    build:
      context: ./core
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - "./core:/app"

  db:
    build:
      context: ./db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
