version: "3"

services:
  core:
    build:
      context: ./core
    environment:
      - PYTHONUNBUFFERED=1

  db:
    build:
      context: ./db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
